export const Cards = [
  {
    img: require("../../../images/hornpc.png"),
    header: "Marketing",
    tag1: "• Digital Marketing",
    tag2: "• Designing",
    tag3: "• Marketing Consulting",
    tag4: "• Event Management",
  },
  {
    img: require("../../../images/moneybag.png"),
    header: "Finance",
    tag1: "• Specialzied Accounting",
    tag2: "• Chief Financial Officer",
    tag3: "• Finance Advisory",
    tag4: "• General Accounting",
  },
  {
    img: require("../../../images/manheadphone.png"),
    header: "Consulting",
    tag1: "• General Consulting",
    tag2: "• Specialized Consulting",
    tag3: "• Management Designations",
    tag4: "• Specialized Designations",
  },
  {
    img: require("../../../images/pentablet.png"),
    header: "Media",
    tag1: "• Photographer",
    tag2: "• Videographer",
    tag3: "• AV and Sound Engineer",
    tag4: "• Production Engineer",
  },
  {
    img: require("../../../images/touchpc.png"),
    header: "IT",
    tag1: "• Photographer",
    tag2: "• Videographer",
    tag3: "• AV and Sound Engineer",
    tag4: "• Production Engineer",
  },
  {
    img: require("../../../images/phonelike.png"),
    header: "Social",
    tag1: "• Lifestyle Blogger",
    tag2: "• Fitness Coach",
    tag3: "• Dance Instructor",
    tag4: "",
  },
];
