const Categories = [
  {
    id: 1,
    cardHeader: "Freelance Visa Dubai – What is it, and how can you obtain it?",
    date: "3 Days Ago",
    red: "Travel",
    img: require("../../../images/blogimg1.png"),
    category: "Travel",
    links: "/blog/blog1",
  },
  {
    id: 2,
    cardHeader: "How to Avoid Overstay Fine in Dubai",
    date: "May 2, 2022",
    red: "Visa",
    img: require("../../../images/blogimg2.png"),
    category: "Visa",
    links: "/blog/blog2",
  },
  {
    id: 3,
    cardHeader:
      "Start Your Freelance Career in the UAE: Things you must consider while getting started with freelancing in Dubai.",
    date: "April 14, 2022",
    red: "Freelance",
    img: require("../../../images/blogimg3.png"),
    category: "Freelance",
    links: "/blog/blog3",
  },
  {
    id: 4,
    cardHeader: "Requirements for all passengers arriving in Dubai",
    date: "Dec 2, 2021",
    red: "Travel",
    img: require("../../../images/blogimg4.jpg"),
    category: "Travel",
    links: "/blog/blog1",
  },
  {
    id: 5,
    cardHeader: "Freelance Visa Dubai – What is it, and how can you obtain it?",
    date: "3 Days Ago",
    red: "Travel",
    img: require("../../../images/blogimg1.png"),
    category: "Travel",
    links: "/blog/blog1",
  },
  {
    id: 6,
    cardHeader: "How to Avoid Overstay Fine in Dubai",
    date: "May 2, 2022",
    red: "Visa",
    img: require("../../../images/blogimg2.png"),
    category: "Visa",
    links: "/blog/blog1",
  },
  {
    id: 7,
    cardHeader:
      "Start Your Freelance Career in the UAE: Things you must consider while getting started with freelancing in Dubai.",
    date: "April 14, 2022",
    red: "Freelance",
    img: require("../../../images/blogimg3.png"),
    category: "Freelance",
    links: "/blog/blog1",
  },
  {
    id: 8,
    cardHeader:
      "Start Your Freelance Career in the UAE: Things you must consider while getting started with freelancing in Dubai.",
    date: "April 14, 2022",
    red: "Freelance",
    img: require("../../../images/blogimg3.png"),
    category: "Freelance",
    links: "/blog/blog1",
  },
  {
    id: 9,
    cardHeader: "How to Avoid Overstay Fine in Dubai",
    date: "May 2, 2022",
    red: "Visa",
    img: require("../../../images/blogimg2.png"),
    category: "Visa",
    links: "/blog/blog1",
  },
];

export default Categories;
